# https://hub.docker.com/_/microsoft-dotnet
FROM dhi.io/dotnet:10-sdk-alpine3.23 AS build
WORKDIR /src

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy everything else and build app
COPY . .
RUN dotnet publish NumberGenerator.csproj -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine3.23
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=build /app .
ENTRYPOINT ["dotnet", "NumberGenerator.dll"]