services:
  frontend:
    build: ./Frontend/numbergenerator
    ports:
      - "80:80"
  numbergenerator:
    build: ./NumberGenerator
    ports:
      - "8080:8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ALLOWED_ORIGIN_STRING=${ALLOWED_ORIGIN_STRING}
      - DB_CONNECTION_STRING_NUMBERGENERATOR=${DB_CONNECTION_STRING_NUMBERGENERATOR}
      - OPENID_AUTHORITY=${OPENID_AUTHORITY}
      - OPENID_CLIENT_ID=${OPENID_CLIENT_ID}
      - OPENID_CLIENT_SECRET=${OPENID_CLIENT_SECRET}
    healthcheck:
      test: curl --fail http://localhost:8080/health
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_numbergenerator:
        condition: service_healthy

  postgres_numbergenerator:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=numbergenerator
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s

  rabbitmq:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.2
    command: start-dev
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASS}
