services:
  numbergenerator:
    build: ./NumberGenerator
    ports:
      - "5238:5283"
    environment:
      - RABBIT_HOSTSTRING=rabbitmq:5672
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
  rabbitmq:
    image: "rabbitmq:4-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
