{
 "title": "TokenService Logs",
 "refresh": "5s",
 "panels": [
  {
   "title": "WalletService Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"tokenservice-api\"} | json | filetype = \"walletController\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.message}}\""
    }
   ]
  },
  {
   "title": "TransactionService Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"tokenservice-api\"} | json | filetype = \"transactionController\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.message}}\""
    }
   ]
  },
  {
   "title": "Startup Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"tokenservice-api\"} | json | filetype = \"startup\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.message}}\""
    }
   ]
  }
 ]
}