{
 "title": "NumberGenerator Logs",
 "refresh": "5s",
 "panels": [
  {
   "title": "HealthService Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"numbergenerator-api\"} | json | SourceContext = \"HealthService\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.Message}}\""
    }
   ]
  },
  {
   "title": "NumberService Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"numbergenerator-api\"} | json | SourceContext = \"NumberService\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.Message}}\""
    }
   ]
  },
  {
   "title": "RabbitMQService Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"numbergenerator-api\"} | json | SourceContext = \"NumberGenerator.Services.RabbitMqService\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.Message}}\""
    }
   ]
  },
  {
   "title": "RabbitMQHelperService Logs",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "{app=\"numbergenerator-api\"} | json | SourceContext = \"NumberGenerator.Services.MqHelperService\" | line_format \"{{ date \\\"02.01.2006 15:04:05\\\" __timestamp__ }} {{.Message}}\""
    }
   ]
  }
 ]
}